version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:  
  # Download .NET Core 2.0 Preview 2 SDK and add to PATH
  - ps: $urlCurrent = "https://download.microsoft.com/download/F/A/A/FAAE9280-F410-458E-8819-279C5A68EDCF/dotnet-sdk-2.0.0-preview2-006497-win-x64.zip"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFileCurrent = [System.IO.Path]::GetTempFileName()
  - ps: (New-Object System.Net.WebClient).DownloadFile($urlCurrent, $tempFileCurrent)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFileCurrent, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./PrimeService/PrimeService.csproj --verbosity m
  - choco install "msbuild-sonarqube-runner" -y
  - MSBuild.SonarQube.Runner.exe begin /k:"test-dotnet-taey" /d:"sonar.host.url=http://kpc-sonar.kingpowerclick.com" /n:"test-dotnet-taey" /v:"1.0.0" /d:sonar.cs.opencover.reportsPaths="xunit-results.xml"
build_script:
  - msbuild /t:rebuild
after_build:
  # For once the build has completed
# artifacts:
#  - path: '\src\bin\Debug\netcoreapp1.1\publish'
#    name: WebSite
#    type: WebDeployPackage
clone_depth: 0
test_script:
  - cmd: dotnet restore ./PrimeService.Tests/PrimeService.Tests.csproj --verbosity m
  - cmd: dotnet test ./PrimeService.Tests/PrimeService.Tests.csproj
on_finish :
  - ps: Push-AppveyorArtifact ".\xunit-results.xml"
  - MSBuild.SonarQube.Runner.exe end
deploy: off